### ISSUE TITLE
Import on fresh site broken on master.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#95]
I think data import with a fresh deployment is broken on master.  Today I tried on our intended production server with commit 48c894b1b5a, and on my dev box (having completely removed the database, removed the node_modules/ directory, and in general tried to make the box completely fresh and as similar to prod as possible) with commit b775600b1d.  I'll file one ticket even though the trees are slightly different and the corresponding symptoms are different -- it's not yet clear if there is one bug or two bugs here.  Assigning to self because prod needs to get deployed tonight, but @trystant please take a look at this issue if it's still open when you see it.  It's pretty important if we can't deploy master.

In both cases I went through the INSTALL.md steps in the usual way, and nothing in the setup seems amiss.

On prod with commit 48c894b1b5a (this is the one I reported in IRC earlier today):

    deploy@getasmokealarm:~/smoke-alarm-portal$ time node data/import_into_postgres.js
    BEGINNING: Mon Aug 03 2015 19:06:57 GMT-0400 (EDT)
    Unhandled rejection SequelizeValidationError: 631 is not a valid string
        at TEXT.validate (/home/deploy/smoke-alarm-portal/node_modules/sequelize/lib/data-types.js:156:11)
        at Object.QueryGenerator.escape (/home/deploy/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query-generator.js:894:20)
        at Object.<anonymous> (/home/deploy/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query-generator.js:356:23)
        at Array.map (native)
        at Object.<anonymous> (/home/deploy/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query-generator.js:352:23)
        at arrayEach (/home/deploy/smoke-alarm-portal/node_modules/sequelize/node_modules/lodash/index.js:1289:13)
        at Function.<anonymous> (/home/deploy/smoke-alarm-portal/node_modules/sequelize/node_modules/lodash/index.js:3345:13)
        at Object.QueryGenerator.bulkInsertQuery (/home/deploy/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query-generator.js:350:13)
        at QueryInterface.bulkInsert (/home/deploy/smoke-alarm-portal/node_modules/sequelize/lib/query-interface.js:575:33)
        at /home/deploy/smoke-alarm-portal/node_modules/sequelize/lib/model.js:2068:34
        at tryCatcher (/home/deploy/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/home/deploy/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
        at Promise._settlePromiseAt (/home/deploy/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)
        at Promise._settlePromises (/home/deploy/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:693:14)
        at Async._drainQueue (/home/deploy/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/async.js:123:16)
        at Async._drainQueues (/home/deploy/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
    
    real    0m19.658s
    user    0m7.996s
    sys     0m0.784s

On my refreshed dev environment with commit b775600b1d:

    $ time node data/import_into_postgres.js
    BEGINNING: Mon Aug 03 2015 21:59:44 GMT-0500 (CDT)
    Unhandled rejection SequelizeDatabaseError: type "json" does not exist
        at Query.formatError (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:429:14)
        at null.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query.js:108:19)
        at emit (events.js:95:17)
        at Query.handleError (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/query.js:108:8)
        at null.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/client.js:171:26)
        at emit (events.js:95:17)
        at Socket.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/pg/lib/connection.js:109:12)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:765:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:427:10)
        at emitReadable (_stream_readable.js:423:5)
        at readableAddChunk (_stream_readable.js:166:9)
        at Socket.Readable.push (_stream_readable.js:128:10)
        at TCP.onread (net.js:529:21)
    Unhandled rejection SequelizeValidationError: 631 is not a valid string
        at TEXT.validate (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/data-types.js:156:11)
        at Object.QueryGenerator.escape (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query-generator.js:894:20)
        at Object.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query-generator.js:356:23)
        at Array.map (native)
        at Object.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query-generator.js:352:23)
        at arrayEach (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/node_modules/lodash/index.js:1289:13)
        at Function.<anonymous> (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/node_modules/lodash/index.js:3345:13)
        at Object.QueryGenerator.bulkInsertQuery (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/dialects/postgres/query-generator.js:350:13)
        at QueryInterface.bulkInsert (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/query-interface.js:575:33)
        at /home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/lib/model.js:2068:34
        at tryCatcher (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
        at Promise._settlePromiseAt (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)
        at Promise._settlePromises (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:693:14)
        at Async._drainQueue (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/async.js:123:16)
        at Async._drainQueues (/home/kfogel/private/work/ots/client/red-cross/r/smoke-alarm-portal/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
    
    real	0m13.341s
    user	0m7.620s
    sys	0m0.348s
    $

**Comment by kfogel** [comment]
Note that if you Google "Unhandled rejection SequelizeDatabaseError: type json does not exist" (with the double quotes), the lone hit is our very own issue #44 :-).

**Comment by kfogel** [comment]
Okay, the `type "json" does not exist` error is solved via commit ba94007 -- it's just a PostgreSQL version mixup thing.

Resolving that unshadowed the `631 is not a valid string` error on my dev box too, so yay, at least we have a reproducible error.  Working on that now.

**Comment by kfogel** [comment]
Got it: `data/usAddresses.json` varies between raw integers and strings in the `area_codes` field.  When `area_codes` is empty its value is a string (""), and when there are two or more area codes its value is also a string (e.g., "508,774").  But when it has exactly one code, then it's an integer.

This is the same species insanity that led the original providers of this file to make zip codes be strings when they start with 0 but integers otherwise.  I cannot even imagine what it must be like to go through life thinking that's a reasonable way to ship data.  Do your friends look down in embarrassment when you talk about work?  Do you end up on some kind of watch list that makes border crossings harder?  Do kittens bare their teeth when they see you coming?

All of the above, probably.

**Comment by kfogel** [comment]
Oh, great.  Once we get past that, there's the problem that all of the "latitude" values are also thought by the model to be strings when in fact they are numbers (but consistently so, at least -- they're all floating point numbers, on both sides of 0, with two decimal places of precision).

**Comment by trystant** [comment]
I

**Comment by trystant** [comment]
I'm also running into this [issue](http://grandkru.com/images/import_into_postgres_error.png) while trying to do an import.

**Comment by kfogel** [comment]
Good point, @trystant.

On production: Node v0.10.38, PostgreSQL 9.4.4, npm 1.4.21
On demo: exactly the same as on prod
On my dev environment: exactly the same as on prod

**Comment by kfogel** [comment]
Is this still an issue?  I've now done several imports into fresh databases, with no problem...

**Comment by cecilia-donnelly** [comment]
Since we haven't had any other reports of problems, I'm closing this.
